bool a = 45 == 67;
bool b = 45 < 67;
bool c = 45 <= 67;
bool d = 45 > 67;
bool e = 45 >= 67;
bool f = 45 != 67;
Console.WriteLine(a);
Console.WriteLine(b);
Console.WriteLine(c);
Console.WriteLine(d);
Console.WriteLine(e);
Console.WriteLine(f);